server:
  port: 8081

spring:
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongodb:27017/zengcode-config}
      database: zengcode-config

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9093}
  segment-bytes: 104857600

mongock:
  enabled: true
  migration-scan-package: com.zengcode.config.repository.changelog

aws:
  s3:
    region: ${AWS_S3_REGION:ap-southeast-1}
    access-key: ${AWS_S3_ACCESS_KEY:dummy}
    secret-key: ${AWS_S3_SECRET_KEY:dummy}
    bucket:
      name: ${AWS_S3_BUCKET_NAME:zengcode-config}
      folder:
        incoming: ${AWS_S3_BUCKET_FOLDER_INCOMING:incoming/}
        completed: ${AWS_S3_BUCKET_FOLDER_COMPLETED:completed/}
        error: ${AWS_S3_BUCKET_FOLDER_ERROR:error/}

config:
  polling:
    period-ms: ${CONFIG_POLLING_PERIOD_MS:30000}