server:
  port: 8081

spring:
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      uri: mongodb://localhost:27017/zengcode-config
      database: zengcode-config

kafka:
  bootstrap-servers: localhost:9093
  segment-bytes: 104857600

mongock:
  enabled: true
  migration-scan-package: com.zengcode.config.repository.changelog

aws:
  s3:
    region: ap-southeast-1
    access-key:
    secret-key:
    bucket:
      name: zengcode-config
      folder:
        incoming: "incoming/"
        completed: "completed/"
        error: "error/"

config:
  polling:
    period-ms: 30000
