server:
  port: 8081

spring:
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      uri: mongodb://localhost:27017/zengcode-config
      database: zengcode-config

kafka:
  bootstrap-servers: localhost:9093
  segment-bytes: 104857600

mongock:
  enabled: true
  migration-scan-package: com.zengcode.config.repository.changelog

zengcode:
  config:
    service: customer-service
    version: 1.0.0
    env: dev
    kafka:
      boot-strap: localhost:9093